// 일본어 단어 데이터 (일상 단어, 동사, 형용사 등)
const VOCABULARY = [
  { word: "水", reading: "みず", meaning: "물" },
  { word: "火", reading: "ひ", meaning: "불" },
  { word: "人", reading: "ひと", meaning: "사람" },
  { word: "山", reading: "やま", meaning: "산" },
  { word: "川", reading: "かわ", meaning: "강" },
  { word: "木", reading: "き", meaning: "나무" },
  { word: "花", reading: "はな", meaning: "꽃" },
  { word: "本", reading: "ほん", meaning: "책" },
  { word: "車", reading: "くるま", meaning: "자동차" },
  { word: "電車", reading: "でんしゃ", meaning: "전철" },
  { word: "食べる", reading: "たべる", meaning: "먹다" },
  { word: "飲む", reading: "のむ", meaning: "마시다" },
  { word: "行く", reading: "いく", meaning: "가다" },
  { word: "来る", reading: "くる", meaning: "오다" },
  { word: "見る", reading: "みる", meaning: "보다" },
  { word: "聞く", reading: "きく", meaning: "듣다" },
  { word: "話す", reading: "はなす", meaning: "말하다" },
  { word: "読む", reading: "よむ", meaning: "읽다" },
  { word: "書く", reading: "かく", meaning: "쓰다" },
  { word: "勉強", reading: "べんきょう", meaning: "공부" },
  { word: "仕事", reading: "しごと", meaning: "일" },
  { word: "学校", reading: "がっこう", meaning: "학교" },
  { word: "友達", reading: "ともだち", meaning: "친구" },
  { word: "家族", reading: "かぞく", meaning: "가족" },
  { word: "今日", reading: "きょう", meaning: "오늘" },
  { word: "明日", reading: "あした", meaning: "내일" },
  { word: "昨日", reading: "きのう", meaning: "어제" },
  { word: "大きい", reading: "おおきい", meaning: "크다" },
  { word: "小さい", reading: "ちいさい", meaning: "작다" },
  { word: "新しい", reading: "あたらしい", meaning: "새롭다" },
  { word: "古い", reading: "ふるい", meaning: "오래되다" },
  { word: "暑い", reading: "あつい", meaning: "덥다" },
  { word: "寒い", reading: "さむい", meaning: "춥다" },
  { word: "美味しい", reading: "おいしい", meaning: "맛있다" },
  { word: "好き", reading: "すき", meaning: "좋아하다" },
  { word: "ありがとう", reading: "ありがとう", meaning: "감사합니다" },
  { word: "すみません", reading: "すみません", meaning: "죄송합니다" },
  { word: "おはよう", reading: "おはよう", meaning: "좋은 아침" },
  { word: "こんにちは", reading: "こんにちは", meaning: "안녕하세요" },
];
